apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solar-system-dev
  namespace: ${NAMESPACE}
  annotations:
    # Disables automatic HTTP->HTTPS redirect while testing without SSL certs
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  # Updated annotation to modern K8s spec
  ingressClassName: nginx
  rules:
    - host: ${INGRESS_HOST}
      http:
        paths:
          - path: /dev(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: solar-system
                port:
                  number: 3000
